### ISSUE TITLE
Linux, Cannot install shm

### ISSUE THREAD

**Issue by andreabenini** [supipd/node-shm#5]
```
[root@host nodejs]# npm install shm
npm http GET https://registry.npmjs.org/shm
npm http 304 https://registry.npmjs.org/shm

> shm@0.1.0 install /opt/PM/nodejs/node_modules/shm
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/bin/gyp", line 18, in <module>
    sys.exit(gyp.main(sys.argv[1:]))
  File "/usr/lib/python2.6/site-packages/gyp/__init__.py", line 462, in main
    options.circular_check)
  File "/usr/lib/python2.6/site-packages/gyp/__init__.py", line 100, in Load
    depth, generator_input_info, check, circular_check)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 2254, in Load
    depth, check)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 361, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 216, in LoadOneBuildFile
    build_file_data = eval(build_file_contents, {'__builtins__': None}, None)
  File "binding.gyp", line 4
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:428:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-279.11.1.el6.i686
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/PM/nodejs/node_modules/shm
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
[root@host nodejs]# cat /etc/redhat-release 
CentOS release 6.4 (Final)
```

What's wrong with it ? I cannot install this module at all
Here are more information

```
[root@host nodejs]# node -v
v0.10.36
[root@host nodejs]# node-gyp -v
v0.10.6
```

npm installed from EPEL repository and nothing more in my application directory, what can I debug to solve it ?

**Comment by supipd** [comment]
it seem's like a not recommended version of Python by node-gyp. 
Recommended is  Python 2.7. I had problems with Python version too.
See  https://github.com/TooTallNate/node-gyp 
or http://stackoverflow.com/questions/20454199/how-to-use-a-different-version-of-python-duing-npm-install

**Comment by andreabenini** [comment]
I have solved without using npm with the official repo.
With "npm install git://<your github url>" I have solved :)
git downloaded the repository and my host compiled the node package, quite easy.
python 2.6 is the version used on every production server based on CentOS 6.x, that's why I'm using it
